sudo: false

language: java

jdk: openjdk10

install:
- ./gradlew -version
- sudo add-apt-repository ppa:wpilib/toolchain -y
- sudo apt-get update -q
- sudo apt-get install frc-toolchain -y 
  
script:
- ./gradlew build
